[package]
name = "dependagot-rust-cargo"
version = "0.1.0"

[dependencies]
bytes = "0.4"
futures = "0.1"
hyper = "0.11"
prost = "0.3"
prost-twirp = "0.1.0"
prost-derive = "0.3"
serde_json = "1.0"
dependagot-common = { path = "../common/" }
