FROM ruby:2.6-slim-buster

RUN mkdir /app
COPY common /app/common

WORKDIR /app/bundler
COPY bundler/Gemfile bundler/Gemfile.lock bundler/dependabot-ruby-bundler.gemspec /app/bundler/
RUN bundle install

COPY bundler /app/bundler/
