# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: dependabot/v1/dependabot.proto for package 'dependabot.v1'

require 'grpc'
require 'dependabot/v1/dependabot_pb'

module Dependabot
  module V1
    module UpdateService
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'dependabot.v1.UpdateService'

        # Files uploads data and returns a list of paths of interest
        # Clients should loop until required_paths is empty, 
        # and fail if required_paths can't be loaded.
        rpc :Files, FilesRequest, FilesResponse
        rpc :ListDependencies, ListDependenciesRequest, ListDependenciesResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
