# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dependabot/v1/dependabot.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("dependabot/v1/dependabot.proto", :syntax => :proto3) do
    add_message "dependabot.v1.FilesRequest" do
    end
    add_message "dependabot.v1.FilesResponse" do
      repeated :paths, :string, 1
    end
  end
end

module Dependabot
  module V1
    FilesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dependabot.v1.FilesRequest").msgclass
    FilesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dependabot.v1.FilesResponse").msgclass
  end
end
