// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dependabot/v1/dependabot.proto

package dependabot_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetupRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetupRequest) Reset()         { *m = SetupRequest{} }
func (m *SetupRequest) String() string { return proto.CompactTextString(m) }
func (*SetupRequest) ProtoMessage()    {}
func (*SetupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c0e8ee9522243d, []int{0}
}

func (m *SetupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupRequest.Unmarshal(m, b)
}
func (m *SetupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupRequest.Marshal(b, m, deterministic)
}
func (m *SetupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupRequest.Merge(m, src)
}
func (m *SetupRequest) XXX_Size() int {
	return xxx_messageInfo_SetupRequest.Size(m)
}
func (m *SetupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetupRequest proto.InternalMessageInfo

type SetupResponse struct {
	SandboxId            string   `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetupResponse) Reset()         { *m = SetupResponse{} }
func (m *SetupResponse) String() string { return proto.CompactTextString(m) }
func (*SetupResponse) ProtoMessage()    {}
func (*SetupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c0e8ee9522243d, []int{1}
}

func (m *SetupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupResponse.Unmarshal(m, b)
}
func (m *SetupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupResponse.Marshal(b, m, deterministic)
}
func (m *SetupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupResponse.Merge(m, src)
}
func (m *SetupResponse) XXX_Size() int {
	return xxx_messageInfo_SetupResponse.Size(m)
}
func (m *SetupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetupResponse proto.InternalMessageInfo

func (m *SetupResponse) GetSandboxId() string {
	if m != nil {
		return m.SandboxId
	}
	return ""
}

type FilesRequest struct {
	SandboxId            string   `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilesRequest) Reset()         { *m = FilesRequest{} }
func (m *FilesRequest) String() string { return proto.CompactTextString(m) }
func (*FilesRequest) ProtoMessage()    {}
func (*FilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c0e8ee9522243d, []int{2}
}

func (m *FilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilesRequest.Unmarshal(m, b)
}
func (m *FilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilesRequest.Marshal(b, m, deterministic)
}
func (m *FilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilesRequest.Merge(m, src)
}
func (m *FilesRequest) XXX_Size() int {
	return xxx_messageInfo_FilesRequest.Size(m)
}
func (m *FilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilesRequest proto.InternalMessageInfo

func (m *FilesRequest) GetSandboxId() string {
	if m != nil {
		return m.SandboxId
	}
	return ""
}

type FilesResponse struct {
	RequiredPaths        []string `protobuf:"bytes,1,rep,name=required_paths,json=requiredPaths,proto3" json:"required_paths,omitempty"`
	OptionalPaths        []string `protobuf:"bytes,2,rep,name=optional_paths,json=optionalPaths,proto3" json:"optional_paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilesResponse) Reset()         { *m = FilesResponse{} }
func (m *FilesResponse) String() string { return proto.CompactTextString(m) }
func (*FilesResponse) ProtoMessage()    {}
func (*FilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c0e8ee9522243d, []int{3}
}

func (m *FilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilesResponse.Unmarshal(m, b)
}
func (m *FilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilesResponse.Marshal(b, m, deterministic)
}
func (m *FilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilesResponse.Merge(m, src)
}
func (m *FilesResponse) XXX_Size() int {
	return xxx_messageInfo_FilesResponse.Size(m)
}
func (m *FilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FilesResponse proto.InternalMessageInfo

func (m *FilesResponse) GetRequiredPaths() []string {
	if m != nil {
		return m.RequiredPaths
	}
	return nil
}

func (m *FilesResponse) GetOptionalPaths() []string {
	if m != nil {
		return m.OptionalPaths
	}
	return nil
}

func init() {
	proto.RegisterType((*SetupRequest)(nil), "dependabot.v1.SetupRequest")
	proto.RegisterType((*SetupResponse)(nil), "dependabot.v1.SetupResponse")
	proto.RegisterType((*FilesRequest)(nil), "dependabot.v1.FilesRequest")
	proto.RegisterType((*FilesResponse)(nil), "dependabot.v1.FilesResponse")
}

func init() {
	proto.RegisterFile("dependabot/v1/dependabot.proto", fileDescriptor_01c0e8ee9522243d)
}

var fileDescriptor_01c0e8ee9522243d = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0x89, 0xb2, 0x42, 0x87, 0xcd, 0x1e, 0x72, 0x5a, 0xfc, 0xc7, 0x52, 0x10, 0xf6, 0x62,
	0x96, 0xd5, 0x37, 0xd8, 0x83, 0xe0, 0x4d, 0x5a, 0x3c, 0x4a, 0x49, 0xcd, 0x80, 0x81, 0x92, 0xa4,
	0x49, 0x5a, 0x7c, 0x13, 0x5f, 0x57, 0x1a, 0x53, 0x6c, 0xa9, 0xe0, 0x71, 0xbe, 0xfc, 0xf2, 0x31,
	0xbf, 0x81, 0x5b, 0x89, 0x16, 0xb5, 0x14, 0xb5, 0x09, 0x87, 0xfe, 0x78, 0xf8, 0x9d, 0xb8, 0x75,
	0x26, 0x18, 0x46, 0x27, 0x49, 0x7f, 0xcc, 0x37, 0xb0, 0x2e, 0x31, 0x74, 0xb6, 0xc0, 0xb6, 0x43,
	0x1f, 0x72, 0x0e, 0x34, 0xcd, 0xde, 0x1a, 0xed, 0x91, 0xdd, 0x00, 0x78, 0xa1, 0x65, 0x6d, 0x3e,
	0x2b, 0x25, 0xb7, 0x64, 0x47, 0xf6, 0x59, 0x91, 0xa5, 0xe4, 0x59, 0xe6, 0xf7, 0xb0, 0x7e, 0x52,
	0x0d, 0xfa, 0xf4, 0xff, 0x3f, 0xfc, 0x0d, 0x68, 0xc2, 0x53, 0xfd, 0x1d, 0x6c, 0x1c, 0xb6, 0x9d,
	0x72, 0x28, 0x2b, 0x2b, 0xc2, 0x87, 0xdf, 0x92, 0xdd, 0xf9, 0x3e, 0x2b, 0xe8, 0x98, 0xbe, 0x0c,
	0xe1, 0x80, 0x19, 0x1b, 0x94, 0xd1, 0xa2, 0x49, 0xd8, 0xd9, 0x0f, 0x36, 0xa6, 0x11, 0x7b, 0xf8,
	0x22, 0x40, 0x5f, 0xad, 0x14, 0x01, 0x4b, 0x74, 0xbd, 0x7a, 0x47, 0x76, 0x82, 0x55, 0xf4, 0x61,
	0x57, 0x7c, 0x26, 0xce, 0xa7, 0xd6, 0x97, 0xd7, 0x7f, 0x3f, 0xa6, 0x1d, 0x4f, 0xb0, 0x8a, 0x4b,
	0x2f, 0x3a, 0xa6, 0xe6, 0x8b, 0x8e, 0x99, 0x67, 0x7d, 0x11, 0xaf, 0xff, 0xf8, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0x56, 0x03, 0xc8, 0x68, 0x9f, 0x01, 0x00, 0x00,
}
