// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dependabot/v1/dependabot.proto

package dependabot_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FilesRequest struct {
	// Data for the update context, indexed by path
	Files                map[string][]byte `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FilesRequest) Reset()         { *m = FilesRequest{} }
func (m *FilesRequest) String() string { return proto.CompactTextString(m) }
func (*FilesRequest) ProtoMessage()    {}
func (*FilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c0e8ee9522243d, []int{0}
}

func (m *FilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilesRequest.Unmarshal(m, b)
}
func (m *FilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilesRequest.Marshal(b, m, deterministic)
}
func (m *FilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilesRequest.Merge(m, src)
}
func (m *FilesRequest) XXX_Size() int {
	return xxx_messageInfo_FilesRequest.Size(m)
}
func (m *FilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilesRequest proto.InternalMessageInfo

func (m *FilesRequest) GetFiles() map[string][]byte {
	if m != nil {
		return m.Files
	}
	return nil
}

type FilesResponse struct {
	// Paths essential to parsing the update
	RequiredPaths        []string `protobuf:"bytes,1,rep,name=required_paths,json=requiredPaths,proto3" json:"required_paths,omitempty"`
	OptionalPaths        []string `protobuf:"bytes,2,rep,name=optional_paths,json=optionalPaths,proto3" json:"optional_paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilesResponse) Reset()         { *m = FilesResponse{} }
func (m *FilesResponse) String() string { return proto.CompactTextString(m) }
func (*FilesResponse) ProtoMessage()    {}
func (*FilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c0e8ee9522243d, []int{1}
}

func (m *FilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilesResponse.Unmarshal(m, b)
}
func (m *FilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilesResponse.Marshal(b, m, deterministic)
}
func (m *FilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilesResponse.Merge(m, src)
}
func (m *FilesResponse) XXX_Size() int {
	return xxx_messageInfo_FilesResponse.Size(m)
}
func (m *FilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FilesResponse proto.InternalMessageInfo

func (m *FilesResponse) GetRequiredPaths() []string {
	if m != nil {
		return m.RequiredPaths
	}
	return nil
}

func (m *FilesResponse) GetOptionalPaths() []string {
	if m != nil {
		return m.OptionalPaths
	}
	return nil
}

type ListDependenciesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDependenciesRequest) Reset()         { *m = ListDependenciesRequest{} }
func (m *ListDependenciesRequest) String() string { return proto.CompactTextString(m) }
func (*ListDependenciesRequest) ProtoMessage()    {}
func (*ListDependenciesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c0e8ee9522243d, []int{2}
}

func (m *ListDependenciesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDependenciesRequest.Unmarshal(m, b)
}
func (m *ListDependenciesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDependenciesRequest.Marshal(b, m, deterministic)
}
func (m *ListDependenciesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDependenciesRequest.Merge(m, src)
}
func (m *ListDependenciesRequest) XXX_Size() int {
	return xxx_messageInfo_ListDependenciesRequest.Size(m)
}
func (m *ListDependenciesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDependenciesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDependenciesRequest proto.InternalMessageInfo

type Dependency struct {
	Package              string   `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dependency) Reset()         { *m = Dependency{} }
func (m *Dependency) String() string { return proto.CompactTextString(m) }
func (*Dependency) ProtoMessage()    {}
func (*Dependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c0e8ee9522243d, []int{3}
}

func (m *Dependency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dependency.Unmarshal(m, b)
}
func (m *Dependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dependency.Marshal(b, m, deterministic)
}
func (m *Dependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dependency.Merge(m, src)
}
func (m *Dependency) XXX_Size() int {
	return xxx_messageInfo_Dependency.Size(m)
}
func (m *Dependency) XXX_DiscardUnknown() {
	xxx_messageInfo_Dependency.DiscardUnknown(m)
}

var xxx_messageInfo_Dependency proto.InternalMessageInfo

func (m *Dependency) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *Dependency) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type ListDependenciesResponse struct {
	Dependencies         []*Dependency `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListDependenciesResponse) Reset()         { *m = ListDependenciesResponse{} }
func (m *ListDependenciesResponse) String() string { return proto.CompactTextString(m) }
func (*ListDependenciesResponse) ProtoMessage()    {}
func (*ListDependenciesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c0e8ee9522243d, []int{4}
}

func (m *ListDependenciesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDependenciesResponse.Unmarshal(m, b)
}
func (m *ListDependenciesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDependenciesResponse.Marshal(b, m, deterministic)
}
func (m *ListDependenciesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDependenciesResponse.Merge(m, src)
}
func (m *ListDependenciesResponse) XXX_Size() int {
	return xxx_messageInfo_ListDependenciesResponse.Size(m)
}
func (m *ListDependenciesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDependenciesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDependenciesResponse proto.InternalMessageInfo

func (m *ListDependenciesResponse) GetDependencies() []*Dependency {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func init() {
	proto.RegisterType((*FilesRequest)(nil), "dependabot.v1.FilesRequest")
	proto.RegisterMapType((map[string][]byte)(nil), "dependabot.v1.FilesRequest.FilesEntry")
	proto.RegisterType((*FilesResponse)(nil), "dependabot.v1.FilesResponse")
	proto.RegisterType((*ListDependenciesRequest)(nil), "dependabot.v1.ListDependenciesRequest")
	proto.RegisterType((*Dependency)(nil), "dependabot.v1.Dependency")
	proto.RegisterType((*ListDependenciesResponse)(nil), "dependabot.v1.ListDependenciesResponse")
}

func init() {
	proto.RegisterFile("dependabot/v1/dependabot.proto", fileDescriptor_01c0e8ee9522243d)
}

var fileDescriptor_01c0e8ee9522243d = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcd, 0x4a, 0xfb, 0x40,
	0x14, 0xc5, 0x99, 0x96, 0xfe, 0xff, 0xf4, 0xda, 0x48, 0x19, 0x04, 0xd3, 0x2a, 0x52, 0x02, 0x6a,
	0x57, 0x2d, 0xad, 0x9b, 0x22, 0x0a, 0x22, 0xea, 0xca, 0x85, 0x8c, 0xb8, 0x70, 0x21, 0x32, 0x4d,
	0xae, 0x3a, 0xb4, 0x64, 0xa6, 0x99, 0x69, 0xa0, 0x2f, 0xe0, 0x33, 0xf9, 0x78, 0x92, 0xcc, 0xa4,
	0x1f, 0xf1, 0x6b, 0x97, 0x73, 0xe6, 0x97, 0xc9, 0xb9, 0xe7, 0x06, 0x0e, 0x22, 0x54, 0x18, 0x47,
	0x7c, 0x2c, 0x4d, 0x3f, 0x1d, 0xf4, 0x57, 0xaa, 0xa7, 0x12, 0x69, 0x24, 0xf5, 0xd6, 0x9c, 0x74,
	0x10, 0xbc, 0x13, 0x68, 0xdc, 0x88, 0x29, 0x6a, 0x86, 0xb3, 0x39, 0x6a, 0x43, 0xcf, 0xa0, 0xf6,
	0x92, 0x69, 0x9f, 0x74, 0xaa, 0xdd, 0xad, 0xe1, 0x51, 0x6f, 0x83, 0xef, 0xad, 0xb3, 0x56, 0x5c,
	0xc7, 0x26, 0x59, 0x30, 0xfb, 0x52, 0x7b, 0x04, 0xb0, 0x32, 0x69, 0x13, 0xaa, 0x13, 0x5c, 0xf8,
	0xa4, 0x43, 0xba, 0x75, 0x96, 0x3d, 0xd2, 0x1d, 0xa8, 0xa5, 0x7c, 0x3a, 0x47, 0xbf, 0xd2, 0x21,
	0xdd, 0x06, 0xb3, 0xe2, 0xb4, 0x32, 0x22, 0xc1, 0x13, 0x78, 0xee, 0x6e, 0xad, 0x64, 0xac, 0x91,
	0x1e, 0xc2, 0x76, 0x82, 0xb3, 0xb9, 0x48, 0x30, 0x7a, 0x56, 0xdc, 0xbc, 0xd9, 0x44, 0x75, 0xe6,
	0x15, 0xee, 0x5d, 0x66, 0x66, 0x98, 0x54, 0x46, 0xc8, 0x98, 0x4f, 0x1d, 0x56, 0xb1, 0x58, 0xe1,
	0xe6, 0x58, 0xd0, 0x82, 0xdd, 0x5b, 0xa1, 0xcd, 0x55, 0x3e, 0x0c, 0xc6, 0xa1, 0x58, 0x4e, 0x11,
	0x5c, 0x00, 0x2c, 0xed, 0x05, 0xf5, 0xe1, 0xbf, 0xe2, 0xe1, 0x84, 0xbf, 0xa2, 0xcb, 0x5d, 0xc8,
	0xec, 0x24, 0xc5, 0x44, 0x0b, 0x19, 0xe7, 0xe9, 0xeb, 0xac, 0x90, 0xc1, 0x23, 0xf8, 0x5f, 0x2f,
	0x77, 0x63, 0x9c, 0x43, 0x23, 0x5a, 0xf3, 0x5d, 0xad, 0xad, 0x52, 0xad, 0xab, 0x00, 0x6c, 0x03,
	0x1f, 0x7e, 0x10, 0xf0, 0x1e, 0x54, 0xc4, 0x0d, 0xde, 0x63, 0x92, 0x8a, 0x10, 0xe9, 0x25, 0xd4,
	0xf2, 0xa2, 0xe8, 0xde, 0x2f, 0xab, 0x69, 0xef, 0x7f, 0x7f, 0xe8, 0x42, 0x85, 0xd0, 0x2c, 0x07,
	0xa6, 0xe5, 0x4d, 0xff, 0x50, 0x57, 0xfb, 0xf8, 0x4f, 0xce, 0x7e, 0x64, 0xfc, 0x2f, 0xff, 0xe1,
	0x4e, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x69, 0xe6, 0xf3, 0x92, 0x02, 0x00, 0x00,
}
