[package]
name = "dependagot-common"
version = "0.1.0"

[dependencies]
bytes = "0.4"
futures = "0.1"
hyper = "0.11"
prost = "0.3"
prost-twirp = "0.1.0"
prost-derive = "0.3"
serde_json = "1.0"

[build-dependencies]
prost-build = "0.3"
prost-twirp = { version = "0.1.0", features = ["service-gen"] }
