# Code generated by protoc-gen-twirp_ruby 1.5.0, DO NOT EDIT.
require 'twirp'
require_relative 'dependagot_pb.rb'

module Dependagot
  module V1
    class UpdateServiceService < Twirp::Service
      package 'dependagot.v1'
      service 'UpdateService'
      rpc :Files, FilesRequest, FilesResponse, :ruby_method => :files
      rpc :ListDependencies, ListDependenciesRequest, ListDependenciesResponse, :ruby_method => :list_dependencies
      rpc :UpdateDependencies, UpdateDependenciesRequest, UpdateDependenciesResponse, :ruby_method => :update_dependencies
    end

    class UpdateServiceClient < Twirp::Client
      client_for UpdateServiceService
    end
  end
end
