# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dependagot/v1/dependagot.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("dependagot/v1/dependagot.proto", :syntax => :proto3) do
    add_message "dependagot.v1.Dependency" do
      optional :package, :string, 1
      optional :version, :string, 2
    end
    add_message "dependagot.v1.FilesRequest" do
      map :files, :string, :bytes, 1
    end
    add_message "dependagot.v1.FilesResponse" do
      repeated :required_paths, :string, 1
      repeated :optional_paths, :string, 2
    end
    add_message "dependagot.v1.ListDependenciesRequest" do
    end
    add_message "dependagot.v1.ListDependenciesResponse" do
      repeated :dependencies, :message, 1, "dependagot.v1.Dependency"
    end
    add_message "dependagot.v1.UpdateDependenciesRequest" do
      repeated :dependencies, :message, 1, "dependagot.v1.Dependency"
    end
    add_message "dependagot.v1.UpdateDependenciesResponse" do
      map :new_files, :string, :string, 1
    end
  end
end

module Dependagot
  module V1
    Dependency = Google::Protobuf::DescriptorPool.generated_pool.lookup("dependagot.v1.Dependency").msgclass
    FilesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("dependagot.v1.FilesRequest").msgclass
    FilesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("dependagot.v1.FilesResponse").msgclass
    ListDependenciesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("dependagot.v1.ListDependenciesRequest").msgclass
    ListDependenciesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("dependagot.v1.ListDependenciesResponse").msgclass
    UpdateDependenciesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("dependagot.v1.UpdateDependenciesRequest").msgclass
    UpdateDependenciesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("dependagot.v1.UpdateDependenciesResponse").msgclass
  end
end
