// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dependagot/v1/dependagot.proto

package dependagot_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Dependency struct {
	Package              string   `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dependency) Reset()         { *m = Dependency{} }
func (m *Dependency) String() string { return proto.CompactTextString(m) }
func (*Dependency) ProtoMessage()    {}
func (*Dependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_965d688b73bac041, []int{0}
}

func (m *Dependency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dependency.Unmarshal(m, b)
}
func (m *Dependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dependency.Marshal(b, m, deterministic)
}
func (m *Dependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dependency.Merge(m, src)
}
func (m *Dependency) XXX_Size() int {
	return xxx_messageInfo_Dependency.Size(m)
}
func (m *Dependency) XXX_DiscardUnknown() {
	xxx_messageInfo_Dependency.DiscardUnknown(m)
}

var xxx_messageInfo_Dependency proto.InternalMessageInfo

func (m *Dependency) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *Dependency) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type FilesRequest struct {
	// Data for the update context, indexed by path
	Files                map[string][]byte `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FilesRequest) Reset()         { *m = FilesRequest{} }
func (m *FilesRequest) String() string { return proto.CompactTextString(m) }
func (*FilesRequest) ProtoMessage()    {}
func (*FilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_965d688b73bac041, []int{1}
}

func (m *FilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilesRequest.Unmarshal(m, b)
}
func (m *FilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilesRequest.Marshal(b, m, deterministic)
}
func (m *FilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilesRequest.Merge(m, src)
}
func (m *FilesRequest) XXX_Size() int {
	return xxx_messageInfo_FilesRequest.Size(m)
}
func (m *FilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilesRequest proto.InternalMessageInfo

func (m *FilesRequest) GetFiles() map[string][]byte {
	if m != nil {
		return m.Files
	}
	return nil
}

type FilesResponse struct {
	// Paths essential to parsing the update
	RequiredPaths        []string `protobuf:"bytes,1,rep,name=required_paths,json=requiredPaths,proto3" json:"required_paths,omitempty"`
	OptionalPaths        []string `protobuf:"bytes,2,rep,name=optional_paths,json=optionalPaths,proto3" json:"optional_paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilesResponse) Reset()         { *m = FilesResponse{} }
func (m *FilesResponse) String() string { return proto.CompactTextString(m) }
func (*FilesResponse) ProtoMessage()    {}
func (*FilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_965d688b73bac041, []int{2}
}

func (m *FilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilesResponse.Unmarshal(m, b)
}
func (m *FilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilesResponse.Marshal(b, m, deterministic)
}
func (m *FilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilesResponse.Merge(m, src)
}
func (m *FilesResponse) XXX_Size() int {
	return xxx_messageInfo_FilesResponse.Size(m)
}
func (m *FilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FilesResponse proto.InternalMessageInfo

func (m *FilesResponse) GetRequiredPaths() []string {
	if m != nil {
		return m.RequiredPaths
	}
	return nil
}

func (m *FilesResponse) GetOptionalPaths() []string {
	if m != nil {
		return m.OptionalPaths
	}
	return nil
}

type ListDependenciesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDependenciesRequest) Reset()         { *m = ListDependenciesRequest{} }
func (m *ListDependenciesRequest) String() string { return proto.CompactTextString(m) }
func (*ListDependenciesRequest) ProtoMessage()    {}
func (*ListDependenciesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_965d688b73bac041, []int{3}
}

func (m *ListDependenciesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDependenciesRequest.Unmarshal(m, b)
}
func (m *ListDependenciesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDependenciesRequest.Marshal(b, m, deterministic)
}
func (m *ListDependenciesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDependenciesRequest.Merge(m, src)
}
func (m *ListDependenciesRequest) XXX_Size() int {
	return xxx_messageInfo_ListDependenciesRequest.Size(m)
}
func (m *ListDependenciesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDependenciesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDependenciesRequest proto.InternalMessageInfo

type ListDependenciesResponse struct {
	Dependencies         []*Dependency `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListDependenciesResponse) Reset()         { *m = ListDependenciesResponse{} }
func (m *ListDependenciesResponse) String() string { return proto.CompactTextString(m) }
func (*ListDependenciesResponse) ProtoMessage()    {}
func (*ListDependenciesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_965d688b73bac041, []int{4}
}

func (m *ListDependenciesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDependenciesResponse.Unmarshal(m, b)
}
func (m *ListDependenciesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDependenciesResponse.Marshal(b, m, deterministic)
}
func (m *ListDependenciesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDependenciesResponse.Merge(m, src)
}
func (m *ListDependenciesResponse) XXX_Size() int {
	return xxx_messageInfo_ListDependenciesResponse.Size(m)
}
func (m *ListDependenciesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDependenciesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDependenciesResponse proto.InternalMessageInfo

func (m *ListDependenciesResponse) GetDependencies() []*Dependency {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

type UpdateDependenciesRequest struct {
	Dependencies         []*Dependency `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateDependenciesRequest) Reset()         { *m = UpdateDependenciesRequest{} }
func (m *UpdateDependenciesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDependenciesRequest) ProtoMessage()    {}
func (*UpdateDependenciesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_965d688b73bac041, []int{5}
}

func (m *UpdateDependenciesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDependenciesRequest.Unmarshal(m, b)
}
func (m *UpdateDependenciesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDependenciesRequest.Marshal(b, m, deterministic)
}
func (m *UpdateDependenciesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDependenciesRequest.Merge(m, src)
}
func (m *UpdateDependenciesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDependenciesRequest.Size(m)
}
func (m *UpdateDependenciesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDependenciesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDependenciesRequest proto.InternalMessageInfo

func (m *UpdateDependenciesRequest) GetDependencies() []*Dependency {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

type UpdateDependenciesResponse struct {
	NewFiles             map[string]string `protobuf:"bytes,1,rep,name=new_files,json=newFiles,proto3" json:"new_files,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateDependenciesResponse) Reset()         { *m = UpdateDependenciesResponse{} }
func (m *UpdateDependenciesResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateDependenciesResponse) ProtoMessage()    {}
func (*UpdateDependenciesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_965d688b73bac041, []int{6}
}

func (m *UpdateDependenciesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDependenciesResponse.Unmarshal(m, b)
}
func (m *UpdateDependenciesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDependenciesResponse.Marshal(b, m, deterministic)
}
func (m *UpdateDependenciesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDependenciesResponse.Merge(m, src)
}
func (m *UpdateDependenciesResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateDependenciesResponse.Size(m)
}
func (m *UpdateDependenciesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDependenciesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDependenciesResponse proto.InternalMessageInfo

func (m *UpdateDependenciesResponse) GetNewFiles() map[string]string {
	if m != nil {
		return m.NewFiles
	}
	return nil
}

func init() {
	proto.RegisterType((*Dependency)(nil), "dependagot.v1.Dependency")
	proto.RegisterType((*FilesRequest)(nil), "dependagot.v1.FilesRequest")
	proto.RegisterMapType((map[string][]byte)(nil), "dependagot.v1.FilesRequest.FilesEntry")
	proto.RegisterType((*FilesResponse)(nil), "dependagot.v1.FilesResponse")
	proto.RegisterType((*ListDependenciesRequest)(nil), "dependagot.v1.ListDependenciesRequest")
	proto.RegisterType((*ListDependenciesResponse)(nil), "dependagot.v1.ListDependenciesResponse")
	proto.RegisterType((*UpdateDependenciesRequest)(nil), "dependagot.v1.UpdateDependenciesRequest")
	proto.RegisterType((*UpdateDependenciesResponse)(nil), "dependagot.v1.UpdateDependenciesResponse")
	proto.RegisterMapType((map[string]string)(nil), "dependagot.v1.UpdateDependenciesResponse.NewFilesEntry")
}

func init() {
	proto.RegisterFile("dependagot/v1/dependagot.proto", fileDescriptor_965d688b73bac041)
}

var fileDescriptor_965d688b73bac041 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x5d, 0x6b, 0xe2, 0x40,
	0x14, 0x25, 0x11, 0x77, 0x37, 0x77, 0xcd, 0x22, 0xc3, 0xc2, 0xc6, 0xec, 0xb2, 0x48, 0x60, 0x77,
	0xdd, 0x97, 0x88, 0xf6, 0xa1, 0xd2, 0x0f, 0x28, 0xa5, 0xed, 0x53, 0x29, 0x25, 0x6d, 0x1f, 0x5a,
	0x28, 0x92, 0x26, 0xb7, 0x76, 0x50, 0x26, 0x31, 0x19, 0x23, 0xfe, 0x81, 0xfe, 0x91, 0xfe, 0x80,
	0xfe, 0xc5, 0x92, 0xcc, 0xa8, 0x31, 0x6a, 0x15, 0xfa, 0x96, 0x73, 0xee, 0x99, 0x7b, 0xef, 0x9c,
	0x33, 0x81, 0xdf, 0x3e, 0x86, 0xc8, 0x7c, 0xb7, 0x17, 0xf0, 0x66, 0xd2, 0x6a, 0xce, 0x91, 0x1d,
	0x46, 0x01, 0x0f, 0x88, 0x9e, 0x63, 0x92, 0x96, 0x75, 0x04, 0x70, 0x92, 0x11, 0xc8, 0xbc, 0x09,
	0x31, 0xe0, 0x73, 0xe8, 0x7a, 0x7d, 0xb7, 0x87, 0x86, 0x52, 0x57, 0x1a, 0x9a, 0x33, 0x85, 0x69,
	0x25, 0xc1, 0x28, 0xa6, 0x01, 0x33, 0x54, 0x51, 0x91, 0xd0, 0x7a, 0x56, 0xa0, 0x72, 0x46, 0x07,
	0x18, 0x3b, 0x38, 0x1c, 0x61, 0xcc, 0xc9, 0x01, 0x94, 0x1f, 0x53, 0x6c, 0x28, 0xf5, 0x52, 0xe3,
	0x6b, 0xfb, 0xaf, 0xbd, 0x30, 0xd1, 0xce, 0x6b, 0x05, 0x38, 0x65, 0x3c, 0x9a, 0x38, 0xe2, 0x90,
	0xd9, 0x01, 0x98, 0x93, 0xa4, 0x0a, 0xa5, 0x3e, 0x4e, 0xe4, 0x32, 0xe9, 0x27, 0xf9, 0x0e, 0xe5,
	0xc4, 0x1d, 0x8c, 0x30, 0x5b, 0xa3, 0xe2, 0x08, 0xb0, 0xa7, 0x76, 0x14, 0xeb, 0x1e, 0x74, 0xd9,
	0x3b, 0x0e, 0x03, 0x16, 0x23, 0xf9, 0x03, 0xdf, 0x22, 0x1c, 0x8e, 0x68, 0x84, 0x7e, 0x37, 0x74,
	0xf9, 0x93, 0xd8, 0x48, 0x73, 0xf4, 0x29, 0x7b, 0x99, 0x92, 0xa9, 0x2c, 0x08, 0x39, 0x0d, 0x98,
	0x3b, 0x90, 0x32, 0x55, 0xc8, 0xa6, 0x6c, 0x26, 0xb3, 0x6a, 0xf0, 0xe3, 0x9c, 0xc6, 0x7c, 0xe6,
	0x16, 0x9d, 0xdd, 0xc2, 0xba, 0x05, 0x63, 0xb9, 0x24, 0x97, 0x38, 0x84, 0x8a, 0x9f, 0xe3, 0xa5,
	0x29, 0xb5, 0x82, 0x29, 0xf3, 0x0c, 0x9c, 0x05, 0xb9, 0x75, 0x07, 0xb5, 0x9b, 0xd0, 0x77, 0x39,
	0xae, 0x98, 0xfb, 0xd1, 0xde, 0xaf, 0x0a, 0x98, 0xab, 0x9a, 0xcb, 0xcd, 0xaf, 0x41, 0x63, 0x38,
	0xee, 0xe6, 0xb3, 0xdc, 0x2d, 0xb4, 0x5e, 0x7f, 0xda, 0xbe, 0xc0, 0x71, 0x2e, 0xdc, 0x2f, 0x4c,
	0x42, 0x73, 0x1f, 0xf4, 0x85, 0xd2, 0xa6, 0x88, 0xb5, 0x5c, 0xc4, 0xed, 0x17, 0x15, 0x74, 0x31,
	0xf3, 0x0a, 0xa3, 0x84, 0x7a, 0x48, 0x8e, 0xa1, 0x9c, 0xf5, 0x22, 0x3f, 0xdf, 0x79, 0x66, 0xe6,
	0xaf, 0xd5, 0x45, 0x79, 0x51, 0x0f, 0xaa, 0xc5, 0xf8, 0x48, 0xf1, 0xd5, 0xae, 0x89, 0xde, 0xfc,
	0xb7, 0x51, 0x27, 0x87, 0x50, 0x20, 0xcb, 0x6e, 0x91, 0xc6, 0x16, 0x86, 0x8a, 0x41, 0xff, 0xb7,
	0xb6, 0xfe, 0xe1, 0x53, 0xf6, 0xa7, 0xef, 0xbc, 0x05, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xe5, 0x0b,
	0x48, 0x0b, 0x04, 0x00, 0x00,
}
